# Generated by Django 3.1.5 on 2024-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('photo', models.CharField(max_length=50, verbose_name='用户头像')),
                ('weChat', models.CharField(max_length=30, verbose_name='微信')),
                ('level', models.CharField(max_length=1, verbose_name='用户等级')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
