# Generated by Django 3.1.5 on 2024-05-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app5', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgfile',
            name='headimg',
            field=models.FileField(upload_to='uploads/', verbose_name='文件名'),
        ),
    ]
