# Generated by Django 3.1.5 on 2024-05-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=30, verbose_name='用户名称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('status', models.BooleanField(max_length=1, verbose_name='状态')),
                ('createdate', models.DateTimeField(db_column='create_date', verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '人员基本信息',
                'db_table': 'UserBaseInfo2',
            },
        ),
    ]
